version: "3.7"

services:
  app:
    networks:
      - internal
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: express-test-docker
  mongo:
    image: mongo:latest
    volumes:
      - "./data:/data/db"
    networks:
      - internal

networks:
  internal:

volumes:
  mongo-volume:

